import Foundation

enum BeginnerContent {
    static let lessons: [BeginnerLesson] = englishLessons

    static func lessons(for language: TargetLanguage) -> [BeginnerLesson] {
        switch language {
        case .english: englishLessons
        case .french: frenchLessons
        case .spanish, .italian: []
        }
    }

    static func firstLessonID(for language: TargetLanguage) -> String {
        lessons(for: language).first?.id ?? englishLessons[0].id
    }

    static func lesson(id: String) -> BeginnerLesson? {
        (frenchLessons + englishLessons).first { $0.id == id }
    }

    static func vocabPracticeLesson(for language: TargetLanguage) -> BeginnerLesson {
        switch language {
        case .english:
            lesson(id: "english-small-talk") ?? englishLessons[1]
        case .french, .spanish, .italian:
            lesson(id: "beginner-greetings") ?? frenchLessons[1]
        }
    }

    static func verbPracticeLesson(for language: TargetLanguage) -> BeginnerLesson {
        switch language {
        case .english:
            lesson(id: "english-work-chat") ?? englishLessons[12]
        case .french, .spanish, .italian:
            lesson(id: "beginner-hotel") ?? frenchLessons[4]
        }
    }

    private static func phrase(_ term: String, _ translation: String, _ example: String) -> SavedWord {
        SavedWord(term: term, translation: translation, example: example)
    }

    private static func englishConversationLesson(
        id: String,
        unit: Int,
        title: String,
        subtitle: String,
        icon: String,
        accent: LessonAccent,
        minutes: Int,
        goal: String,
        model: String,
        modelHelper: String,
        speak: String,
        speakHelper: String,
        alternative: String,
        alternativeHelper: String,
        mistakePrompt: String,
        correctAnswer: String,
        commonMistake: String,
        roleplay: String,
        roleplayHelper: String,
        followUp: String,
        followUpHelper: String,
        savedWords: [SavedWord],
        extraMistake: String = ""
    ) -> BeginnerLesson {
        let answerChoices = [correctAnswer, commonMistake, extraMistake].filter { !$0.isEmpty }

        return BeginnerLesson(
            id: id,
            unit: unit,
            title: title,
            subtitle: subtitle,
            icon: icon,
            accent: accent,
            minutes: minutes,
            steps: [
                LessonStep(id: "\(id)-goal", kind: .teach, title: "Speaking goal", prompt: goal, helper: "Say the goal first so your brain knows the job.", choices: [], correctAnswer: nil),
                LessonStep(id: "\(id)-model", kind: .teach, title: "Listen and repeat", prompt: model, helper: modelHelper, choices: [], correctAnswer: nil),
                LessonStep(id: "\(id)-speak", kind: .speak, title: "Say it your way", prompt: speak, helper: speakHelper, choices: [], correctAnswer: nil),
                LessonStep(id: "\(id)-alternative", kind: .speak, title: "Natural alternative", prompt: alternative, helper: alternativeHelper, choices: [], correctAnswer: nil),
                LessonStep(id: "\(id)-mistake", kind: .choice, title: "Common mistake", prompt: mistakePrompt, helper: "Choose the clear line, then say it out loud.", choices: answerChoices, correctAnswer: correctAnswer),
                LessonStep(id: "\(id)-roleplay", kind: .speak, title: "Roleplay", prompt: roleplay, helper: roleplayHelper, choices: [], correctAnswer: nil),
                LessonStep(id: "\(id)-follow-up", kind: .speak, title: "Follow-up practice", prompt: followUp, helper: followUpHelper, choices: [], correctAnswer: nil)
            ],
            savedWords: savedWords
        )
    }

    private static func frenchConversationLesson(
        id: String,
        unit: Int,
        title: String,
        subtitle: String,
        icon: String,
        accent: LessonAccent,
        minutes: Int,
        goal: String,
        model: String,
        modelHelper: String,
        speak: String,
        speakHelper: String,
        nextLine: String,
        nextLineHelper: String,
        checkPrompt: String,
        correctAnswer: String,
        commonMistake: String,
        extraMistake: String,
        roleplay: String,
        roleplayHelper: String,
        followUp: String,
        followUpHelper: String,
        savedWords: [SavedWord]
    ) -> BeginnerLesson {
        let answerChoices = [correctAnswer, commonMistake, extraMistake].filter { !$0.isEmpty }

        return BeginnerLesson(
            id: id,
            unit: unit,
            title: title,
            subtitle: subtitle,
            icon: icon,
            accent: accent,
            minutes: minutes,
            steps: [
                LessonStep(id: "\(id)-goal", kind: .teach, title: "Speaking goal", prompt: goal, helper: "Keep the line short so it is easy to say.", choices: [], correctAnswer: nil),
                LessonStep(id: "\(id)-model", kind: .teach, title: "Listen and repeat", prompt: model, helper: modelHelper, choices: [], correctAnswer: nil),
                LessonStep(id: "\(id)-speak", kind: .speak, title: "Say it your way", prompt: speak, helper: speakHelper, choices: [], correctAnswer: nil),
                LessonStep(id: "\(id)-next-line", kind: .speak, title: "Natural next line", prompt: nextLine, helper: nextLineHelper, choices: [], correctAnswer: nil),
                LessonStep(id: "\(id)-check", kind: .choice, title: "Clear answer", prompt: checkPrompt, helper: "Choose the natural French line, then say it out loud.", choices: answerChoices, correctAnswer: correctAnswer),
                LessonStep(id: "\(id)-roleplay", kind: .speak, title: "Roleplay", prompt: roleplay, helper: roleplayHelper, choices: [], correctAnswer: nil),
                LessonStep(id: "\(id)-follow-up", kind: .speak, title: "Follow-up practice", prompt: followUp, helper: followUpHelper, choices: [], correctAnswer: nil)
            ],
            savedWords: savedWords
        )
    }

    private static let englishLessons: [BeginnerLesson] = [
        englishConversationLesson(
            id: "english-introductions",
            unit: 1,
            title: "Introduce yourself",
            subtitle: "Start a first conversation without freezing",
            icon: "person.wave.2.fill",
            accent: .blue,
            minutes: 5,
            goal: "My goal is to introduce myself in two calm sentences.",
            model: "Hi, I'm Maya. Nice to meet you.",
            modelHelper: "Use this in class, at work, while traveling, or when a friend introduces you.",
            speak: "Hi, I'm Alex. I'm from Indonesia.",
            speakHelper: "Change Alex and Indonesia to your real name and place.",
            alternative: "You can call me Alex.",
            alternativeHelper: "Use this when you prefer a short name.",
            mistakePrompt: "You want to say where you live.",
            correctAnswer: "I live in Jakarta.",
            commonMistake: "I am live in Jakarta.",
            roleplay: "A new classmate says, Hi, I'm Sara. What should I call you?",
            roleplayHelper: "Answer with your preferred name, then add one small detail.",
            followUp: "I'm learning English because I want to speak more confidently.",
            followUpHelper: "Swap the reason: for work, for travel, for my studies, or for friends.",
            savedWords: [
                phrase("nice to meet you", "polite phrase for a first meeting", "Hi, I'm Maya. Nice to meet you."),
                phrase("I'm from", "use this to say your city or country", "I'm from Indonesia."),
                phrase("you can call me", "say the name you prefer", "You can call me Alex."),
                phrase("I'm learning English because", "explain your reason simply", "I'm learning English because I want to travel.")
            ],
            extraMistake: "I live at Jakarta."
        ),
        englishConversationLesson(
            id: "english-small-talk",
            unit: 1,
            title: "Keep small talk moving",
            subtitle: "Answer a check-in and ask back naturally",
            icon: "bubble.left.fill",
            accent: .mint,
            minutes: 5,
            goal: "My goal is to answer a simple check-in and ask one question back.",
            model: "Pretty good, thanks. How about you?",
            modelHelper: "This keeps the conversation open without needing a long answer.",
            speak: "I'm doing well. I had a quiet morning.",
            speakHelper: "Add one tiny detail if you want to sound natural.",
            alternative: "A little tired, but I'm okay.",
            alternativeHelper: "Use this when the answer is honest but still friendly.",
            mistakePrompt: "Someone asks, How are you today?",
            correctAnswer: "I'm doing well, thanks.",
            commonMistake: "I doing well, thanks.",
            roleplay: "A neighbor says, Morning. How are you today?",
            roleplayHelper: "Answer with one short feeling and ask back.",
            followUp: "It was nice talking to you. See you later.",
            followUpHelper: "Use this to close small talk politely.",
            savedWords: [
                phrase("how's your day going", "friendly question about someone's day", "Hi, how's your day going?"),
                phrase("pretty good, thanks", "natural short answer when you feel okay", "Pretty good, thanks."),
                phrase("how about you", "ask the same question back", "I'm doing well. How about you?"),
                phrase("it was nice talking to you", "polite way to end a short chat", "It was nice talking to you. See you later.")
            ],
            extraMistake: "I am well doing."
        ),
        englishConversationLesson(
            id: "english-daily-routine",
            unit: 1,
            title: "Talk about your day",
            subtitle: "Say a normal routine without overthinking",
            icon: "clock.fill",
            accent: .mint,
            minutes: 5,
            goal: "My goal is to describe one normal day in simple English.",
            model: "I usually start work around nine.",
            modelHelper: "Usually means most days. Around makes the time feel natural.",
            speak: "I usually study English after work.",
            speakHelper: "Change study English to exercise, cook dinner, or call my family.",
            alternative: "Most days, I have coffee before work.",
            alternativeHelper: "Most days is a natural alternative to usually.",
            mistakePrompt: "You want to say when you sleep.",
            correctAnswer: "I go to bed at ten.",
            commonMistake: "I go bed in ten.",
            roleplay: "A friend asks, What do you usually do after work?",
            roleplayHelper: "Answer with one habit, then ask the same question back.",
            followUp: "After work, I usually rest for a bit, then I study English.",
            followUpHelper: "Use then to connect two easy actions.",
            savedWords: [
                phrase("I usually", "start a sentence about a normal habit", "I usually study English at night."),
                phrase("around nine", "about nine o'clock, not exact", "I usually start work around nine."),
                phrase("after work", "later than work ends", "I study English after work."),
                phrase("for a bit", "for a short time", "I rest for a bit, then I study.")
            ],
            extraMistake: "I am go to bed at ten."
        ),
        englishConversationLesson(
            id: "english-free-time",
            unit: 1,
            title: "Talk about free time",
            subtitle: "Share likes and ask a follow-up",
            icon: "figure.walk",
            accent: .violet,
            minutes: 5,
            goal: "My goal is to say what I like and ask about the other person.",
            model: "I like watching movies when I have free time.",
            modelHelper: "This is easy, personal, and useful for friendly conversation.",
            speak: "I like walking around the city on weekends.",
            speakHelper: "Change walking around the city to your real activity.",
            alternative: "I'm into cooking these days.",
            alternativeHelper: "I'm into means I like it right now.",
            mistakePrompt: "You want to say you enjoy music.",
            correctAnswer: "I like listening to music.",
            commonMistake: "I like listen music.",
            roleplay: "A coworker asks, What do you do for fun?",
            roleplayHelper: "Answer with one activity and ask, How about you?",
            followUp: "How about you? What do you like doing on weekends?",
            followUpHelper: "Ask a follow-up so the conversation does not stop.",
            savedWords: [
                phrase("I like watching", "say an activity you enjoy", "I like watching movies."),
                phrase("when I have free time", "when you are not busy", "I read when I have free time."),
                phrase("I'm into", "casual way to say you like something", "I'm into cooking these days."),
                phrase("what do you do for fun", "ask about free-time activities", "What do you do for fun?")
            ],
            extraMistake: "I am like music."
        ),
        englishConversationLesson(
            id: "english-making-plans",
            unit: 1,
            title: "Make simple plans",
            subtitle: "Invite, choose a time, and confirm",
            icon: "calendar.badge.plus",
            accent: .blue,
            minutes: 6,
            goal: "My goal is to suggest a simple plan and confirm the details.",
            model: "Would you like to get coffee tomorrow?",
            modelHelper: "Would you like to is polite and friendly.",
            speak: "Are you free after class?",
            speakHelper: "Use are you free to check availability first.",
            alternative: "Does Saturday afternoon work for you?",
            alternativeHelper: "This checks if the time is okay for the other person.",
            mistakePrompt: "You want to suggest meeting at six.",
            correctAnswer: "Let's meet at six.",
            commonMistake: "Let's meeting at six.",
            roleplay: "A classmate says, I'd like to practice English more. Suggest a time.",
            roleplayHelper: "Ask if they are free, give a time, and check if it works.",
            followUp: "Great, see you there at six.",
            followUpHelper: "Close the plan with the time or place.",
            savedWords: [
                phrase("would you like to", "polite way to invite someone", "Would you like to meet tomorrow?"),
                phrase("are you free", "ask if someone has time", "Are you free after class?"),
                phrase("does Saturday work for you", "ask if a day is okay", "Does Saturday work for you?"),
                phrase("see you there", "confirm the meeting place", "Great, see you there at six.")
            ],
            extraMistake: "We meet on six?"
        ),
        englishConversationLesson(
            id: "english-review-first-chat",
            unit: 1,
            title: "First chat practice",
            subtitle: "Put introductions, small talk, and plans together",
            icon: "checkmark.seal.fill",
            accent: .amber,
            minutes: 7,
            goal: "My goal is to keep a first conversation going for one minute.",
            model: "Hi, I'm Alex. Nice to meet you. How's your day going?",
            modelHelper: "This opens a real conversation with two safe lines.",
            speak: "I'm here for the language meetup.",
            speakHelper: "Use I'm here for to explain the situation.",
            alternative: "I only started recently, so I'm a little nervous.",
            alternativeHelper: "This is honest and easy to say.",
            mistakePrompt: "You want to explain why you are learning English.",
            correctAnswer: "I'm learning English for work.",
            commonMistake: "I learning English for work.",
            roleplay: "You meet a new person at a language meetup. Start the conversation.",
            roleplayHelper: "Use your name, one detail, and one question.",
            followUp: "Would you like to practice together sometime?",
            followUpHelper: "End by making a simple future plan.",
            savedWords: [
                phrase("I'm here for", "explain why you are in a place", "I'm here for the language meetup."),
                phrase("for work", "explain a practical reason", "I'm learning English for work."),
                phrase("sometime", "not a fixed time yet", "Would you like to practice together sometime?"),
                phrase("language meetup", "a place where people practice languages", "I met Sara at a language meetup.")
            ],
            extraMistake: "I learn English because for work."
        ),
        englishConversationLesson(
            id: "english-ordering",
            unit: 2,
            title: "Order food and drinks",
            subtitle: "Order clearly and answer counter questions",
            icon: "cup.and.saucer.fill",
            accent: .amber,
            minutes: 6,
            goal: "My goal is to order at a cafe and answer one follow-up question.",
            model: "Hi, can I get a latte and a croissant, please?",
            modelHelper: "Can I get sounds natural at a cafe counter.",
            speak: "For here, please.",
            speakHelper: "Use this when they ask if you will eat or drink inside.",
            alternative: "That's all for me, thanks.",
            alternativeHelper: "Use this after the worker asks if you want anything else.",
            mistakePrompt: "The cashier asks, For here or to go?",
            correctAnswer: "To go, please.",
            commonMistake: "I go please.",
            roleplay: "The cashier says, We don't have croissants today. Would a muffin be okay?",
            roleplayHelper: "Accept the replacement or choose another item.",
            followUp: "A muffin is fine, thanks.",
            followUpHelper: "Use fine when the replacement works for you.",
            savedWords: [
                phrase("can I get", "natural way to order at a counter", "Can I get a latte, please?"),
                phrase("for here", "say you will eat or drink inside", "For here, please."),
                phrase("to go", "say you will take it away", "To go, please."),
                phrase("that's all for me", "say you do not want more", "That's all for me, thanks.")
            ],
            extraMistake: "For go, please."
        ),
        englishConversationLesson(
            id: "english-restaurant-check",
            unit: 2,
            title: "Ask restaurant questions",
            subtitle: "Check a menu, allergies, and the bill",
            icon: "fork.knife",
            accent: .violet,
            minutes: 6,
            goal: "My goal is to check a dish before I order it.",
            model: "Does this come with rice or salad?",
            modelHelper: "Use come with to ask what is included.",
            speak: "Is there any meat in this soup?",
            speakHelper: "Use is there any when you need to check one ingredient.",
            alternative: "Can you make it without onions?",
            alternativeHelper: "Use without to remove one ingredient.",
            mistakePrompt: "You have an allergy and need to ask about peanuts.",
            correctAnswer: "Does this have peanuts in it?",
            commonMistake: "This has peanuts in it?",
            roleplay: "The server says, It comes with rice. Is that okay?",
            roleplayHelper: "Answer yes or ask for a change before ordering.",
            followUp: "Yes, rice is fine. I'll have that, please.",
            followUpHelper: "Confirm the answer, then place the order.",
            savedWords: [
                phrase("does this come with", "ask what is included", "Does this come with rice or salad?"),
                phrase("is there any", "ask if one thing is inside", "Is there any meat in this soup?"),
                phrase("without onions", "ask to remove an ingredient", "Can you make it without onions?"),
                phrase("rice is fine", "say the option is okay", "Yes, rice is fine.")
            ],
            extraMistake: "This food has peanut?"
        ),
        englishConversationLesson(
            id: "english-directions",
            unit: 2,
            title: "Ask for directions",
            subtitle: "Find a place and check the route",
            icon: "map.fill",
            accent: .blue,
            minutes: 6,
            goal: "My goal is to ask for directions and repeat the answer back.",
            model: "Excuse me, how do I get to the train station?",
            modelHelper: "Use how do I get to when you need the route, not just the place.",
            speak: "Is it far from here?",
            speakHelper: "Ask this before you decide to walk.",
            alternative: "Should I turn left at the traffic lights?",
            alternativeHelper: "Use should I to check one step in the route.",
            mistakePrompt: "You missed the street name.",
            correctAnswer: "Could you say the street name again?",
            commonMistake: "Could say street name again?",
            roleplay: "A local says, Walk two blocks and turn right after the bank.",
            roleplayHelper: "Repeat the route in your own words, then thank them.",
            followUp: "Two blocks, then right after the bank. Thanks.",
            followUpHelper: "Repeat only the key landmarks so the check stays quick.",
            savedWords: [
                phrase("excuse me", "polite way to get attention", "Excuse me, where is the station?"),
                phrase("how do I get to", "ask for the route to a place", "How do I get to the train station?"),
                phrase("is it far from here", "ask about distance", "Is it far from here?"),
                phrase("turn right after", "direction using a landmark", "Turn right after the bank.")
            ],
            extraMistake: "Again the street name please you?"
        ),
        englishConversationLesson(
            id: "english-transport-ticket",
            unit: 2,
            title: "Buy a ticket or ride",
            subtitle: "Ask for tickets, stops, and arrival time",
            icon: "tram.fill",
            accent: .mint,
            minutes: 6,
            goal: "My goal is to ask for a ticket and check where to get off.",
            model: "One adult ticket to City Hall, please.",
            modelHelper: "This works at a station counter or ticket window.",
            speak: "Which platform does it leave from?",
            speakHelper: "Use this after you buy the ticket and need the next step.",
            alternative: "Can I use this ticket on the bus too?",
            alternativeHelper: "Ask this when one ticket might cover another ride.",
            mistakePrompt: "You need to know where to get off for the airport.",
            correctAnswer: "Which stop should I get off at for the airport?",
            commonMistake: "Airport is which stop I get off?",
            roleplay: "The ticket agent says, The next train leaves from platform three at 10:20.",
            roleplayHelper: "Confirm the platform and time, then thank them.",
            followUp: "Platform three at 10:20. Thank you.",
            followUpHelper: "Repeating the detail helps you avoid missing the ride.",
            savedWords: [
                phrase("one adult ticket to", "ask for one ticket to a place", "One adult ticket to City Hall, please."),
                phrase("which platform", "ask where a train leaves", "Which platform does it leave from?"),
                phrase("get off at", "leave a bus or train at a stop", "Which stop should I get off at?"),
                phrase("platform three", "a platform number", "The train leaves from platform three.")
            ],
            extraMistake: "Where I get down for airport?"
        ),
        englishConversationLesson(
            id: "english-shopping-prices",
            unit: 2,
            title: "Shop and pay",
            subtitle: "Ask price, size, and payment questions",
            icon: "bag.fill",
            accent: .amber,
            minutes: 6,
            goal: "My goal is to ask about a product and pay without panic.",
            model: "How much is this jacket?",
            modelHelper: "Use this when you point to one item.",
            speak: "Do you have it in medium?",
            speakHelper: "Change medium to your size or the color you want.",
            alternative: "Can I try it on?",
            alternativeHelper: "Ask this before you go to the fitting room.",
            mistakePrompt: "The shirt is too small and you need a bigger one.",
            correctAnswer: "Do you have a larger size?",
            commonMistake: "You have more big size?",
            roleplay: "The assistant says, This one is 30 dollars, but the blue one is on sale.",
            roleplayHelper: "Ask about the sale item or choose one.",
            followUp: "I'll take the blue one, please.",
            followUpHelper: "Use I'll take when you have decided to buy.",
            savedWords: [
                phrase("how much is this", "ask the price of one thing", "How much is this jacket?"),
                phrase("in medium", "ask for a size", "Do you have it in medium?"),
                phrase("try it on", "put on clothes before buying", "Can I try it on?"),
                phrase("on sale", "available at a lower price", "The blue one is on sale.")
            ],
            extraMistake: "Have this more large?"
        ),
        englishConversationLesson(
            id: "english-ask-for-help",
            unit: 2,
            title: "Ask for help",
            subtitle: "Get someone to repeat, slow down, or explain",
            icon: "questionmark.circle.fill",
            accent: .violet,
            minutes: 6,
            goal: "My goal is to ask for help when I do not understand.",
            model: "Sorry, can you say that again?",
            modelHelper: "This is a simple way to ask for a repeat without freezing.",
            speak: "Could you speak more slowly, please?",
            speakHelper: "Use this when you hear the words but need more time.",
            alternative: "Can you show me where to press?",
            alternativeHelper: "Use this when a person can point or demonstrate.",
            mistakePrompt: "You understood most of the sentence but missed the final step.",
            correctAnswer: "What should I do after that?",
            commonMistake: "What I do after that?",
            roleplay: "A ticket-machine helper says, First choose the station, then tap your card. You do not see the station name.",
            roleplayHelper: "Explain what you cannot find and ask them to show you.",
            followUp: "I can't find the station name. Can you show me?",
            followUpHelper: "Say the exact problem so the other person can help quickly.",
            savedWords: [
                phrase("can you say that again", "ask someone to repeat", "Can you say that again?"),
                phrase("could you speak more slowly", "ask someone to slow down", "Could you speak more slowly, please?"),
                phrase("show me where to press", "ask someone to demonstrate", "Can you show me where to press?"),
                phrase("what should I do after that", "ask for the next step", "What should I do after that?")
            ],
            extraMistake: "After that what I should do?"
        ),
        englishConversationLesson(
            id: "english-work-chat",
            unit: 3,
            title: "Start a work chat",
            subtitle: "Share your role and find the next step",
            icon: "briefcase.fill",
            accent: .blue,
            minutes: 6,
            goal: "My goal is to start a work chat with my role and one useful next step.",
            model: "Hi, I'm Maya. I joined the product team this week.",
            modelHelper: "Use joined to give quick context when you are new.",
            speak: "I work on onboarding, so I'll be helping with the app flow.",
            speakHelper: "Use I work on plus a project, task, or area.",
            alternative: "I'm still getting settled, but it's good to meet you.",
            alternativeHelper: "This sounds friendly without giving a long story.",
            mistakePrompt: "You tell someone the project you work on.",
            correctAnswer: "I'm helping with the onboarding project.",
            commonMistake: "I helping with the onboarding project.",
            roleplay: "A teammate says, Welcome. What will you be working on?",
            roleplayHelper: "Say your area, then ask where to find the current notes.",
            followUp: "Where can I find the latest project notes?",
            followUpHelper: "This moves the chat toward useful work information.",
            savedWords: [
                phrase("joined the product team", "say you recently became part of a team", "I joined the product team this week."),
                phrase("I work on", "say the project or task you handle", "I work on onboarding."),
                phrase("getting settled", "still learning a new workplace", "I'm still getting settled."),
                phrase("latest project notes", "the newest shared information about work", "Where can I find the latest project notes?")
            ],
            extraMistake: "I am help onboarding project."
        ),
        englishConversationLesson(
            id: "english-meeting-check-in",
            unit: 3,
            title: "Give a meeting update",
            subtitle: "Join the check-in and move work forward",
            icon: "person.2.fill",
            accent: .mint,
            minutes: 6,
            goal: "My goal is to give a short meeting update and ask who should act next.",
            model: "Hi everyone. I have a quick update on the timeline.",
            modelHelper: "Name the topic before you give details.",
            speak: "The draft is ready for review.",
            speakHelper: "Give one clear status before you ask for feedback.",
            alternative: "Before we move on, can we choose the next owner?",
            alternativeHelper: "Use this when the meeting needs a clear next person.",
            mistakePrompt: "You need feedback before Thursday.",
            correctAnswer: "I need feedback by Thursday.",
            commonMistake: "I need feedback until Thursday.",
            roleplay: "Your manager says, Let's start with your update.",
            roleplayHelper: "Say what is ready, then say what you need next.",
            followUp: "Who should review the draft next?",
            followUpHelper: "This turns your update into a clear next action.",
            savedWords: [
                phrase("quick update", "a short work status", "I have a quick update on the timeline."),
                phrase("the draft is ready", "say a work item is finished enough to review", "The draft is ready for review."),
                phrase("feedback by Thursday", "a clear deadline for comments", "I need feedback by Thursday."),
                phrase("review the draft", "read and comment on a work item", "Who should review the draft next?")
            ],
            extraMistake: "I need the feedback on Thursday before."
        ),
        englishConversationLesson(
            id: "english-phone-call",
            unit: 3,
            title: "Make a work call",
            subtitle: "Open the call and state the purpose",
            icon: "phone.fill",
            accent: .violet,
            minutes: 6,
            goal: "My goal is to make a short work call and explain why I am calling.",
            model: "Hi, this is Alex from Converlax.",
            modelHelper: "Use this is when you introduce yourself on a call.",
            speak: "I'm calling about the invoice you sent yesterday.",
            speakHelper: "Use I'm calling about plus the topic of the call.",
            alternative: "I only need two minutes.",
            alternativeHelper: "Use this when the call should be short.",
            mistakePrompt: "You check if the person can talk now.",
            correctAnswer: "Is now still a good time to talk?",
            commonMistake: "Now still good time for talk?",
            roleplay: "A supplier answers the phone. Introduce yourself and say why you are calling.",
            roleplayHelper: "Give your name, company, and one clear call topic.",
            followUp: "Could you send the updated time by email?",
            followUpHelper: "End with the exact information you need after the call.",
            savedWords: [
                phrase("this is Alex from", "introduce yourself and your company on a call", "Hi, this is Alex from Converlax."),
                phrase("I'm calling about", "state the purpose of a call", "I'm calling about the invoice."),
                phrase("good time to talk", "ask if someone can talk now", "Is now still a good time to talk?"),
                phrase("send the updated time", "ask for the new schedule", "Could you send the updated time by email?")
            ],
            extraMistake: "It is good time talking now?"
        ),
        englishConversationLesson(
            id: "english-explain-problem",
            unit: 3,
            title: "Explain a problem",
            subtitle: "Report the issue and the next blocker",
            icon: "exclamationmark.bubble.fill",
            accent: .amber,
            minutes: 6,
            goal: "My goal is to explain a work problem with the symptom and what is blocked.",
            model: "I'm having trouble uploading the file.",
            modelHelper: "Use having trouble plus an -ing verb for a simple issue.",
            speak: "The upload stops at 80 percent, so I can't send the report.",
            speakHelper: "Say what happens, then explain why it matters.",
            alternative: "It may be a small issue, but it's blocking my next step.",
            alternativeHelper: "This sounds calm and shows the impact.",
            mistakePrompt: "You report a problem with a work file.",
            correctAnswer: "The report won't open on my laptop.",
            commonMistake: "The report can't open in my laptop.",
            roleplay: "IT asks, What is happening when you upload the file?",
            roleplayHelper: "Name the symptom, then say what you already tried.",
            followUp: "Can I send you a screenshot and the file name?",
            followUpHelper: "Offer the information that helps someone investigate.",
            savedWords: [
                phrase("having trouble uploading", "having a problem sending a file", "I'm having trouble uploading the file."),
                phrase("stops at 80 percent", "describe exactly where a process fails", "The upload stops at 80 percent."),
                phrase("blocking my next step", "preventing the next work action", "It's blocking my next step."),
                phrase("send you a screenshot", "share a picture of the issue", "Can I send you a screenshot?")
            ],
            extraMistake: "The upload stop in 80 percent."
        ),
        englishConversationLesson(
            id: "english-give-opinion",
            unit: 3,
            title: "Give a simple opinion",
            subtitle: "Share a choice and one useful reason",
            icon: "lightbulb.fill",
            accent: .blue,
            minutes: 6,
            goal: "My goal is to give a work opinion with one reason and one next test.",
            model: "I have a small suggestion about the plan.",
            modelHelper: "This opens your opinion gently before you choose.",
            speak: "Option B is clearer for new users.",
            speakHelper: "Give the option and the reason in one short sentence.",
            alternative: "My concern is the launch timing, not the idea itself.",
            alternativeHelper: "This keeps the tone respectful when you raise a concern.",
            mistakePrompt: "You suggest a small test.",
            correctAnswer: "Should we test it with one customer first?",
            commonMistake: "Should we testing it with one customer first?",
            roleplay: "A teammate asks, Which plan should we choose for the first version?",
            roleplayHelper: "Choose one option and give one short work reason.",
            followUp: "What do you think?",
            followUpHelper: "Ask back so the conversation becomes a decision.",
            savedWords: [
                phrase("small suggestion", "a gentle way to offer an idea", "I have a small suggestion."),
                phrase("option B is clearer", "say one choice is easier to understand", "I think option B is clearer."),
                phrase("my concern is", "introduce a worry politely", "My concern is the launch timing."),
                phrase("test it with one customer", "try an idea with one real user first", "Should we test it with one customer first?")
            ],
            extraMistake: "Should test with one customer first?"
        ),
        englishConversationLesson(
            id: "english-agree-disagree",
            unit: 3,
            title: "Agree and disagree politely",
            subtitle: "Support the goal and adjust the plan",
            icon: "hand.thumbsup.fill",
            accent: .mint,
            minutes: 6,
            goal: "My goal is to agree with the goal, explain a concern, and suggest a better next step.",
            model: "I agree with the goal, but I have a concern about the deadline.",
            modelHelper: "Agree with the shared goal before you explain the problem.",
            speak: "Friday gives us one more day to test.",
            speakHelper: "Give a practical reason before you suggest a change.",
            alternative: "That makes sense. I just want to be careful with the timing.",
            alternativeHelper: "This is a softer way to disagree in a team conversation.",
            mistakePrompt: "You suggest a later launch date.",
            correctAnswer: "Can we move the launch to Friday?",
            commonMistake: "Can we moving launch to Friday?",
            roleplay: "A teammate wants to finish the project today, but you think it is too rushed.",
            roleplayHelper: "Support the goal, name the deadline concern, then suggest one change.",
            followUp: "Can we decide the final timeline after we see the draft?",
            followUpHelper: "This keeps the conversation moving toward a team decision.",
            savedWords: [
                phrase("agree with the goal", "support the main purpose", "I agree with the goal."),
                phrase("concern about the deadline", "a worry about timing", "I have a concern about the deadline."),
                phrase("move the launch", "change the launch date", "Maybe we can move the launch to Friday."),
                phrase("final timeline", "the agreed schedule", "Can we decide the final timeline?")
            ],
            extraMistake: "Can we move the launch in Friday?"
        ),
        englishConversationLesson(
            id: "english-hotel-check-in",
            unit: 4,
            title: "Check in at a hotel",
            subtitle: "Give your name and ask practical questions",
            icon: "bed.double.fill",
            accent: .violet,
            minutes: 6,
            goal: "My goal is to check in and handle one practical detail.",
            model: "Good evening. I have a room booked under Alex Tan.",
            modelHelper: "Room booked under names the person on the hotel booking.",
            speak: "I arrived a little early. Is the room ready yet?",
            speakHelper: "Use this when you arrive before the normal check-in time.",
            alternative: "What time does breakfast start?",
            alternativeHelper: "Ask for one useful hotel detail before you leave the desk.",
            mistakePrompt: "You ask reception to write the Wi-Fi password.",
            correctAnswer: "Could you write down the Wi-Fi password?",
            commonMistake: "Can you write the Wi-Fi password down me?",
            roleplay: "The receptionist asks, May I see your passport and card?",
            roleplayHelper: "Give the documents, then ask one practical hotel question.",
            followUp: "Thank you. What time is checkout?",
            followUpHelper: "Ask one final practical detail before leaving the desk.",
            savedWords: [
                phrase("room booked under", "say the hotel booking name", "I have a room booked under Alex Tan."),
                phrase("check in now", "ask if you can start check-in", "Could I check in now?"),
                phrase("not ready yet", "say the room is not available now", "The room is not ready yet."),
                phrase("write down", "ask someone to put information on paper", "Could you write down the Wi-Fi password?")
            ],
            extraMistake: "Could write down Wi-Fi password for me?"
        ),
        englishConversationLesson(
            id: "english-travel-plans",
            unit: 4,
            title: "Talk about travel plans",
            subtitle: "Say where you are going and what you plan to do",
            icon: "airplane.departure",
            accent: .blue,
            minutes: 6,
            goal: "My goal is to explain where I am going, when, and why.",
            model: "I'm staying in Bangkok until Friday.",
            modelHelper: "Use staying in for a temporary visit to a city.",
            speak: "Tomorrow I'm taking the train to the old town.",
            speakHelper: "Use tomorrow plus taking when the travel plan is already arranged.",
            alternative: "I'm here for work, but I have one free evening.",
            alternativeHelper: "Useful when travel is not only for vacation.",
            mistakePrompt: "The plan might change if it rains.",
            correctAnswer: "If it rains, I might visit the market instead.",
            commonMistake: "If rains, I maybe visit the market instead.",
            roleplay: "A hotel guest asks, What are your plans while you're here?",
            roleplayHelper: "Say the city, the day or length, and one flexible activity.",
            followUp: "Is there a quiet place nearby for dinner?",
            followUpHelper: "Ask for one specific local suggestion.",
            savedWords: [
                phrase("I'm staying in", "say where you are visiting now", "I'm staying in Bangkok until Friday."),
                phrase("until Friday", "say when a visit ends", "I'm here until Friday."),
                phrase("taking the train", "say planned transport", "Tomorrow I'm taking the train."),
                phrase("I might", "talk about a possible plan", "I might visit the market instead.")
            ],
            extraMistake: "If it rain, I might visit market."
        ),
        englishConversationLesson(
            id: "english-airport-travel",
            unit: 4,
            title: "Handle airport moments",
            subtitle: "Ask about gates, bags, and delays",
            icon: "airplane",
            accent: .amber,
            minutes: 6,
            goal: "My goal is to ask one clear airport question at a time.",
            model: "Which gate should I go to for flight 218?",
            modelHelper: "Use which gate when you need the gate number for a flight.",
            speak: "The screen says delayed. What is the new boarding time?",
            speakHelper: "Name the delay first, then ask for the updated time.",
            alternative: "My bag did not arrive. Where should I report it?",
            alternativeHelper: "Use report it when baggage is missing or damaged.",
            mistakePrompt: "You need to confirm the boarding time.",
            correctAnswer: "Just to confirm, boarding is at 6:40, right?",
            commonMistake: "Confirm, boarding at 6:40, yes?",
            roleplay: "An airline staff member asks, How can I help you?",
            roleplayHelper: "Choose one issue: gate, delay, baggage, or confirmation.",
            followUp: "Thanks. I'll go to the gate now.",
            followUpHelper: "Close with the next action after you confirm.",
            savedWords: [
                phrase("which gate should I go to", "ask for the correct flight gate", "Which gate should I go to for flight 218?"),
                phrase("the screen says delayed", "say the flight board shows a delay", "The screen says delayed."),
                phrase("my bag did not arrive", "say baggage is missing", "My bag did not arrive."),
                phrase("just to confirm", "check information one more time", "Just to confirm, boarding is at 6:40, right?")
            ],
            extraMistake: "Just confirm boarding 6:40 right?"
        ),
        englishConversationLesson(
            id: "english-emergency-help",
            unit: 4,
            title: "Emergency help phrases",
            subtitle: "Ask for urgent help and say what is wrong",
            icon: "cross.case.fill",
            accent: .blue,
            minutes: 6,
            goal: "My goal is to ask for urgent help in short, direct lines.",
            model: "I need help now. My wallet was stolen.",
            modelHelper: "Use short sentences so the main problem is clear.",
            speak: "My bag is missing.",
            speakHelper: "Say what is wrong before you ask for help.",
            alternative: "Someone is hurt. We need a doctor.",
            alternativeHelper: "Say what happened, then name the help you need.",
            mistakePrompt: "You need security.",
            correctAnswer: "Please call security.",
            commonMistake: "Please call to security.",
            roleplay: "You are at a station and your bag is missing.",
            roleplayHelper: "Say you need help, what is wrong, and who should be called.",
            followUp: "Can you stay here until help comes?",
            followUpHelper: "Ask one person to stay if you need support.",
            savedWords: [
                phrase("I need help now", "direct urgent request", "I need help now."),
                phrase("was stolen", "say someone took something", "My wallet was stolen."),
                phrase("please call security", "ask someone to contact help", "Please call security."),
                phrase("someone is hurt", "say a person needs medical help", "Someone is hurt. We need a doctor.")
            ],
            extraMistake: "Call security please you."
        ),
        englishConversationLesson(
            id: "english-doctor-pharmacy",
            unit: 4,
            title: "Doctor and pharmacy",
            subtitle: "Describe symptoms and ask for medicine",
            icon: "pills.fill",
            accent: .mint,
            minutes: 6,
            goal: "My goal is to explain symptoms, timing, advice, and dosage.",
            model: "I have a fever and a sore throat.",
            modelHelper: "Use I have plus the symptom or symptoms.",
            speak: "It started two days ago.",
            speakHelper: "Say when the symptoms started before asking for medicine.",
            alternative: "Should I see a doctor, or can I take medicine for this?",
            alternativeHelper: "Ask for advice before choosing medicine.",
            mistakePrompt: "You describe stomach pain.",
            correctAnswer: "My stomach hurts.",
            commonMistake: "My stomach is pain.",
            roleplay: "A pharmacist asks, What symptoms do you have?",
            roleplayHelper: "Say your symptoms, how long, and ask what they recommend.",
            followUp: "How many tablets should I take each day?",
            followUpHelper: "Ask the dosage before you leave the pharmacy.",
            savedWords: [
                phrase("I have a fever", "describe a high temperature", "I have a fever."),
                phrase("it started", "say when a problem began", "It started two days ago."),
                phrase("should I see a doctor", "ask if medical care is needed", "Should I see a doctor?"),
                phrase("how many tablets", "ask about medicine dosage", "How many tablets should I take each day?")
            ],
            extraMistake: "I am stomach hurt."
        ),
        englishConversationLesson(
            id: "english-course-wrap-up",
            unit: 4,
            title: "Full conversation practice",
            subtitle: "Use the course phrases in one realistic exchange",
            icon: "checkmark.seal.fill",
            accent: .violet,
            minutes: 8,
            goal: "My goal is to open, ask, clarify, and close a real exchange.",
            model: "Hi, I'm Alex. I'm here for a short work trip.",
            modelHelper: "This gives your name and reason without a long story.",
            speak: "Could I ask where the airport train leaves from?",
            speakHelper: "Ask one practical question with could I ask where.",
            alternative: "Do you know a quiet cafe nearby?",
            alternativeHelper: "Ask for a specific recommendation so the answer is easier to follow.",
            mistakePrompt: "You did not catch the answer and need it again.",
            correctAnswer: "I missed the last part. Could you say it once more?",
            commonMistake: "I didn't hear all. Say again one more?",
            roleplay: "You meet someone near a station. Introduce yourself, ask one practical question, clarify one answer, and close.",
            roleplayHelper: "Use four short lines: who you are, your question, your clarification, and thanks.",
            followUp: "Thanks, that helps. Have a good day.",
            followUpHelper: "Close the exchange without adding extra explanation.",
            savedWords: [
                phrase("short work trip", "brief visit for work", "I'm here for a short work trip."),
                phrase("could I ask where", "start a practical location question", "Could I ask where the train leaves from?"),
                phrase("I missed the last part", "say you did not catch everything", "I missed the last part."),
                phrase("that helps", "say the answer was useful", "Thanks, that helps.")
            ],
            extraMistake: "I missed last part. Could say once more?"
        )
    ]

    private static let frenchLessons: [BeginnerLesson] = [
        frenchConversationLesson(
            id: "beginner-introductions",
            unit: 1,
            title: "Introduce yourself",
            subtitle: "Name, origin, and a polite reply",
            icon: "person.wave.2.fill",
            accent: .blue,
            minutes: 5,
            goal: "My goal is to greet someone and introduce myself in French.",
            model: "Bonjour. Je m'appelle Maya.",
            modelHelper: "Hello. My name is Maya.",
            speak: "Bonjour. Je m'appelle Alex.",
            speakHelper: "Change Alex to your real name.",
            nextLine: "Je viens d'Indonesie.",
            nextLineHelper: "Use je viens de to say where you are from.",
            checkPrompt: "Someone says, Bonjour, je m'appelle Sara.",
            correctAnswer: "Enchante, Sara.",
            commonMistake: "Je voudrais Sara.",
            extraMistake: "Ou est Sara ?",
            roleplay: "You meet a classmate. Say hello, your name, and where you are from.",
            roleplayHelper: "Use Bonjour, je m'appelle..., then Je viens de...",
            followUp: "Et vous ?",
            followUpHelper: "Ask the other person politely.",
            savedWords: [
                phrase("bonjour", "hello", "Bonjour, je m'appelle Maya."),
                phrase("je m'appelle", "my name is", "Je m'appelle Alex."),
                phrase("je viens de", "I come from", "Je viens d'Indonesie."),
                phrase("enchante", "nice to meet you", "Enchante, Sara.")
            ]
        ),
        frenchConversationLesson(
            id: "beginner-greetings",
            unit: 1,
            title: "Greet someone",
            subtitle: "Answer a check-in and ask back",
            icon: "bubble.left.fill",
            accent: .mint,
            minutes: 5,
            goal: "My goal is to answer a simple greeting and keep the exchange moving.",
            model: "Bonjour, comment ca va ?",
            modelHelper: "This means hello, how are you?",
            speak: "Ca va bien, merci.",
            speakHelper: "A simple answer when you are doing well.",
            nextLine: "Et vous ?",
            nextLineHelper: "Use this polite line to ask the same question back.",
            checkPrompt: "A shopkeeper asks, Comment ca va ?",
            correctAnswer: "Tres bien, merci. Et vous ?",
            commonMistake: "Je suis bien merci vous.",
            extraMistake: "Au revoir, ca va gare.",
            roleplay: "A neighbor says, Bonjour.",
            roleplayHelper: "Greet them, ask how they are, and answer simply.",
            followUp: "Au revoir. Bonne journee.",
            followUpHelper: "Use this to close the short exchange politely.",
            savedWords: [
                phrase("comment ca va", "how are you", "Bonjour, comment ca va ?"),
                phrase("ca va bien", "I am doing well", "Ca va bien, merci."),
                phrase("et vous", "and you", "Tres bien, merci. Et vous ?"),
                phrase("au revoir", "goodbye", "Au revoir. Bonne journee.")
            ]
        ),
        frenchConversationLesson(
            id: "beginner-ordering",
            unit: 1,
            title: "Order coffee",
            subtitle: "A short cafe order",
            icon: "cup.and.saucer.fill",
            accent: .amber,
            minutes: 5,
            goal: "My goal is to order one drink politely.",
            model: "Un cafe, s'il vous plait.",
            modelHelper: "A short cafe order: a coffee, please.",
            speak: "Je voudrais un cafe, s'il vous plait.",
            speakHelper: "Je voudrais means I would like.",
            nextLine: "Je voudrais de l'eau, s'il vous plait.",
            nextLineHelper: "Swap the item while keeping the polite frame.",
            checkPrompt: "You want juice.",
            correctAnswer: "Je voudrais un jus, s'il vous plait.",
            commonMistake: "Je suis un jus, s'il vous plait.",
            extraMistake: "Ou est un jus ?",
            roleplay: "The server says, Bonjour, vous desirez ?",
            roleplayHelper: "Order one drink and say merci.",
            followUp: "Merci. C'est tout.",
            followUpHelper: "Use this when you are done ordering.",
            savedWords: [
                phrase("je voudrais", "I would like", "Je voudrais un cafe."),
                phrase("un cafe", "a coffee", "Un cafe, s'il vous plait."),
                phrase("de l'eau", "some water", "Je voudrais de l'eau."),
                phrase("s'il vous plait", "please", "Un cafe, s'il vous plait.")
            ]
        ),
        frenchConversationLesson(
            id: "beginner-directions",
            unit: 1,
            title: "Ask for directions",
            subtitle: "Find a place politely",
            icon: "map.fill",
            accent: .violet,
            minutes: 5,
            goal: "My goal is to ask where a useful place is.",
            model: "Ou est la gare ?",
            modelHelper: "Where is the station?",
            speak: "Excusez-moi, ou est la gare ?",
            speakHelper: "Start with excusez-moi to sound polite.",
            nextLine: "C'est a gauche ?",
            nextLineHelper: "Ask if the place is on the left.",
            checkPrompt: "You need the hotel.",
            correctAnswer: "Excusez-moi, ou est l'hotel ?",
            commonMistake: "Excusez-moi, je suis l'hotel ?",
            extraMistake: "La gare est un cafe.",
            roleplay: "You are near the station and need the hotel.",
            roleplayHelper: "Start with Excusez-moi, then ask where the hotel is.",
            followUp: "Merci, c'est pres ?",
            followUpHelper: "Ask if it is nearby.",
            savedWords: [
                phrase("ou est", "where is", "Ou est la gare ?"),
                phrase("la gare", "the station", "Ou est la gare ?"),
                phrase("a gauche", "on the left", "C'est a gauche."),
                phrase("c'est pres", "it is nearby", "C'est pres ?")
            ]
        ),
        frenchConversationLesson(
            id: "beginner-hotel",
            unit: 1,
            title: "Check in at a hotel",
            subtitle: "Reservation, name, and one question",
            icon: "building.2.fill",
            accent: .blue,
            minutes: 5,
            goal: "My goal is to check in with a reservation.",
            model: "J'ai une reservation.",
            modelHelper: "I have a reservation.",
            speak: "Bonjour, j'ai une reservation.",
            speakHelper: "Say it calmly at the reception desk.",
            nextLine: "Pour deux nuits.",
            nextLineHelper: "Use this to say the stay is for two nights.",
            checkPrompt: "Reception asks for the name on the reservation.",
            correctAnswer: "La reservation est au nom de Martin.",
            commonMistake: "Je suis au nom de Martin.",
            extraMistake: "La gare est au nom de Martin.",
            roleplay: "Reception says, Bonjour, vous avez une reservation ?",
            roleplayHelper: "Answer yes, then give the name on the reservation.",
            followUp: "Est-ce que le petit dejeuner est inclus ?",
            followUpHelper: "Ask one practical hotel question.",
            savedWords: [
                phrase("j'ai", "I have", "J'ai une reservation."),
                phrase("une reservation", "a reservation", "J'ai une reservation."),
                phrase("au nom de", "under the name of", "La reservation est au nom de Martin."),
                phrase("pour deux nuits", "for two nights", "Pour deux nuits.")
            ]
        ),
        frenchConversationLesson(
            id: "beginner-review",
            unit: 1,
            title: "Beginner review",
            subtitle: "One simple travel exchange",
            icon: "checkmark.seal.fill",
            accent: .mint,
            minutes: 6,
            goal: "My goal is to combine greetings, ordering, directions, and hotel check-in.",
            model: "Bonjour. Je m'appelle Alex. Je voudrais un cafe, s'il vous plait.",
            modelHelper: "This combines a greeting, name, and cafe order.",
            speak: "Bonjour. Je m'appelle Alex. Je viens d'Indonesie.",
            speakHelper: "Change the name and place to fit you.",
            nextLine: "Excusez-moi, ou est l'hotel ?",
            nextLineHelper: "Use this when you arrive and need the hotel.",
            checkPrompt: "You are at a cafe and want a croissant.",
            correctAnswer: "Je voudrais un croissant, s'il vous plait.",
            commonMistake: "Je suis un croissant.",
            extraMistake: "Ou est un croissant, merci ?",
            roleplay: "You arrive in a new city. Introduce yourself, order water, then ask for the hotel.",
            roleplayHelper: "Use three short lines. Pause between them.",
            followUp: "Merci. Au revoir.",
            followUpHelper: "Close the exchange simply.",
            savedWords: [
                phrase("merci", "thank you", "Merci. Au revoir."),
                phrase("un croissant", "a croissant", "Je voudrais un croissant."),
                phrase("ou est l'hotel", "where is the hotel", "Ou est l'hotel ?"),
                phrase("j'ai une reservation", "I have a reservation", "J'ai une reservation.")
            ]
        )
    ]
}
